Veins: veins::RoadsOsgVisualizer Class Reference
veins::RoadsOsgVisualizer Class Reference
Simple support module to visualize road network as received via TraCI.
#include <RoadsOsgVisualizer.h>
Public Member Functions
void initialize (int stage) override
Detailed Description
Simple support module to visualize road network as received via TraCI.
See the Veins website for a tutorial, documentation, and publications .
Author
Christoph Sommer
See also
TraCIScenarioManager
Member Function Documentation
void RoadsOsgVisualizer::initialize (int stage) override
References veins::TraCIScenarioManagerAccess::get(), veins::TraCIScenarioManager::getCommandInterface(), veins::TraCICommandInterface::getLaneIds(), veins::TraCICommandInterface::Lane::getShape(), veins::TraCICommandInterface::lane(), and veins::TraCIScenarioManager::traciInitializedSignal.
 {
 }
The documentation for this class was generated from the following files:
RoadsOsgVisualizer.h
RoadsOsgVisualizer.cc