Veins: veins::TraCIScenarioManagerLaunchd Class Reference
veins::TraCIScenarioManagerLaunchd Class Reference
Extends the TraCIScenarioManager for use with sumo-launchd.py and SUMO.
#include <TraCIScenarioManagerLaunchd.h>
Public Member Functions
~TraCIScenarioManagerLaunchd () override
void initialize (int stage) override
void finish () override
Public Member Functions inherited from veins::TraCIScenarioManager
TraCIScenarioManager ()
~TraCIScenarioManager () override
int numInitStages () const override
void initialize (int stage) override
void preNetworkFinish ()
void finish () override
void handleMessage (cMessage *msg) override
virtual void handleSelfMsg (cMessage *msg)
bool isConnected () const
TraCICommandInterface * getCommandInterface () const
TraCIConnection * getConnection () const
bool getAutoShutdownTriggered ()
const std::map< std::string, cModule * > & getManagedHosts ()
bool isUsable () const
Predicate indicating a successful connection to the TraCI server.
Protected Member Functions
void init_traci () override
Protected Member Functions inherited from veins::TraCIScenarioManager
void executeOneTimestep ()
read and execute all commands for the next timestep
virtual void preInitializeModule (cModule *mod, const std::string &nodeId, const Coord &position, const std::string &road_id, double speed, Heading heading, VehicleSignalSet signals)
virtual void updateModulePosition (cModule *mod, const Coord &p, const std::string &edge, double speed, Heading heading, VehicleSignalSet signals)
void addModule (std::string nodeId, std::string type, std::string name, std::string displayString, const Coord &position, std::string road_id="", double speed=-1, Heading heading=Heading::nan, VehicleSignalSet signals={VehicleSignal::undefined}, double length=0, double height=0, double width=0)
cModule * getManagedModule (std::string nodeId)
returns a pointer to the managed module named moduleName, or 0 if no module can be found
void deleteManagedModule (std::string nodeId)
bool isModuleUnequipped (std::string nodeId)
returns true if this vehicle is Unequipped
void subscribeToVehicleVariables (std::string vehicleId)
void unsubscribeFromVehicleVariables (std::string vehicleId)
void processSimSubscription (std::string objectId, TraCIBuffer &buf)
void processVehicleSubscription (std::string objectId, TraCIBuffer &buf)
void processSubcriptionResult (TraCIBuffer &buf)
void subscribeToTrafficLightVariables (std::string tlId)
void unsubscribeFromTrafficLightVariables (std::string tlId)
void processTrafficLightSubscription (std::string objectId, TraCIBuffer &buf)
void parseModuleTypes ()
parses the vector of module types in ini file
TypeMapping parseMappings (std::string parameter, std::string parameterName, bool allowEmpty=false)
transforms a list of mappings of an omnetpp.ini parameter in a list
virtual int getPortNumber () const
void lifecycleEvent (SimulationLifecycleEventType eventType, cObject *details) override
void listenerRemoved () override
Protected Attributes
cXMLElement * launchConfig
launch configuration to send to sumo-launchd
int seed
seed value to set in launch configuration, if missing (-1: current run number)
Protected Attributes inherited from veins::TraCIScenarioManager
bool traciInitialized = false
Flag indicating whether the init_traci routine has been run.
simtime_t connectAt
when to connect to TraCI server (must be the initial timestep of the server)
simtime_t firstStepAt
when to start synchronizing with the TraCI server (-1: immediately after connecting)
simtime_t updateInterval
time interval of hosts' position updates
TypeMapping moduleType
module type to be used in the simulation for each managed vehicle
TypeMapping moduleName
module name to be used in the simulation for each managed vehicle
TypeMapping moduleDisplayString
module displayString to be used in the simulation for each managed vehicle
std::string host
int port
std::string trafficLightModuleType
module type to be used in the simulation for each managed traffic light
std::string trafficLightModuleName
module name to be used in the simulation for each managed traffic light
std::string trafficLightModuleDisplayString
module displayString to be used in the simulation for each managed vehicle
std::vector< std::string > trafficLightModuleIds
list of traffic light module ids that is subscribed to (whitelist)
bool autoShutdown
Shutdown module as soon as no more vehicles are in the simulation.
double penetrationRate
bool ignoreGuiCommands
whether to ignore all TraCI commands that only make sense when the server has a graphical user interface
int order
bool ignoreUnknownSubscriptionResults
TraCIRegionOfInterest roi
Can return whether a given position lies within the simulation's region of interest.
double areaSum
AnnotationManager * annotations
std::unique_ptr< TraCIConnection > connection
std::unique_ptr< TraCICommandInterface > commandIfc
size_t nextNodeVectorIndex
next OMNeT++ module vector index to use
std::map< std::string, cModule * > hosts
vector of all hosts managed by us
std::set< std::string > unEquippedHosts
std::set< std::string > subscribedVehicles
all vehicles we have already subscribed to
std::map< std::string, cModule * > trafficLights
vector of all traffic lights managed by us
uint32_t activeVehicleCount
number of vehicles, be it parking or driving
uint32_t parkingVehicleCount
number of parking vehicles, derived from parking start/end events
uint32_t drivingVehicleCount
number of driving, as reported by sumo
bool autoShutdownTriggered
cMessage * connectAndStartTrigger
self-message scheduled for when to connect to TraCI server and start running
cMessage * executeOneTimestepTrigger
self-message scheduled for when to next call executeOneTimestep
BaseWorldUtility * world
std::map< const BaseMobility *, const MobileHostObstacle * > vehicleObstacles
VehicleObstacleControl * vehicleObstacleControl
Additional Inherited Members
Static Public Attributes inherited from veins::TraCIScenarioManager
static const simsignal_t traciInitializedSignal = registerSignal("org_car2x_veins_modules_mobility_traciInitialized")
static const simsignal_t traciModulePreInitSignal = registerSignal("org_car2x_veins_modules_mobility_traciModulePreInit")
static const simsignal_t traciModuleAddedSignal = registerSignal("org_car2x_veins_modules_mobility_traciModuleAdded")
static const simsignal_t traciModuleRemovedSignal = registerSignal("org_car2x_veins_modules_mobility_traciModuleRemoved")
static const simsignal_t traciTimestepBeginSignal = registerSignal("org_car2x_veins_modules_mobility_traciTimestepBegin")
static const simsignal_t traciTimestepEndSignal = registerSignal("org_car2x_veins_modules_mobility_traciTimestepEnd")
Protected Types inherited from veins::TraCIScenarioManager
typedef std::map< std::string, std::string > TypeMapping
Detailed Description
Extends the TraCIScenarioManager for use with sumo-launchd.py and SUMO.
Connects to a running instance of the sumo-launchd.py script to automatically launch/kill SUMO when the simulation starts/ends.
All other functionality is provided by the TraCIScenarioManager.
See the Veins website for a tutorial, documentation, and publications .
Author
Christoph Sommer, David Eckhoff
See also
TraCIMobility
TraCIScenarioManager
Constructor & Destructor Documentation
TraCIScenarioManagerLaunchd::~TraCIScenarioManagerLaunchd () override
 {
 }
Member Function Documentation
void TraCIScenarioManagerLaunchd::finish () override
References veins::TraCIScenarioManager::finish().
 {
     TraCIScenarioManager::finish();
 }
void TraCIScenarioManagerLaunchd::init_traci () override protected virtual
Reimplemented from veins::TraCIScenarioManager.
References veins::TraCIConstants::CMD_FILE_SEND, veins::TraCIScenarioManager::init_traci(), veins::makeTraCICommand(), and veins::TraCIConstants::RTYPE_OK.
 {
     {
         std::pair<uint32_t, std::string> version = getCommandInterface()->getVersion();
         uint32_t apiVersion = version.first;
         std::string serverVersion = version.second;
         if (apiVersion == 1) {
             EV_DEBUG << "TraCI server \"" << serverVersion << "\" reports API version " << apiVersion << endl;
         }
         else {
             throw cRuntimeError("TraCI server \"%s\" reports API version %d, which is unsupported. We recommend using the version of sumo-launchd that ships with Veins.", serverVersion.c_str(), apiVersion);
         }
     }
 #if OMNETPP_VERSION <= 0x500
     std::string contents = launchConfig->tostr(0);
 #else
     std::string contents = launchConfig->getXML();
 #endif
     TraCIBuffer buf;
     buf << std::string("sumo-launchd.launch.xml") << contents;
     connection->sendMessage(makeTraCICommand(CMD_FILE_SEND, buf));
     TraCIBuffer obuf(connection->receiveMessage());
     uint8_t cmdLength;
     obuf >> cmdLength;
     uint8_t commandResp;
     obuf >> commandResp;
     if (commandResp != CMD_FILE_SEND) throw cRuntimeError("Expected response to command %d, but got one for command %d", CMD_FILE_SEND, commandResp);
     uint8_t result;
     obuf >> result;
     std::string description;
     obuf >> description;
     if (result != RTYPE_OK) {
         EV << "Warning: Received non-OK response from TraCI server to command " << CMD_FILE_SEND << ":" << description.c_str() << std::endl;
     }
     TraCIScenarioManager::init_traci();
 }
void TraCIScenarioManagerLaunchd::initialize (int stage) override
References veins::TraCIScenarioManager::initialize().
 {
     if (stage != 1) {
         TraCIScenarioManager::initialize(stage);
         return;
     }
     launchConfig = par("launchConfig").xmlValue();
     seed = par("seed");
     cXMLElementList basedir_nodes = launchConfig->getElementsByTagName("basedir");
     if (basedir_nodes.size() == 0) {
         // default basedir is where current network file was loaded from
         std::string basedir = cSimulation::getActiveSimulation()->getEnvir()->getConfig()->getConfigEntry("network").getBaseDirectory();
         cXMLElement* basedir_node = new cXMLElement("basedir", __FILE__, launchConfig);
         basedir_node->setAttribute("path", basedir.c_str());
         launchConfig->appendChild(basedir_node);
     }
     cXMLElementList seed_nodes = launchConfig->getElementsByTagName("seed");
     if (seed_nodes.size() == 0) {
         if (seed == -1) {
             // default seed is current repetition
             const char* seed_s = cSimulation::getActiveSimulation()->getEnvir()->getConfigEx()->getVariable(CFGVAR_RUNNUMBER);
             seed = atoi(seed_s);
         }
         std::stringstream ss;
         ss << seed;
         cXMLElement* seed_node = new cXMLElement("seed", __FILE__, launchConfig);
         seed_node->setAttribute("value", ss.str().c_str());
         launchConfig->appendChild(seed_node);
     }
     TraCIScenarioManager::initialize(stage);
 }
Member Data Documentation
cXMLElement* veins::TraCIScenarioManagerLaunchd::launchConfig protected
launch configuration to send to sumo-launchd
int veins::TraCIScenarioManagerLaunchd::seed protected
seed value to set in launch configuration, if missing (-1: current run number)
The documentation for this class was generated from the following files:
TraCIScenarioManagerLaunchd.h
TraCIScenarioManagerLaunchd.cc